
name: Juno Tests

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the spring-boot branch
  #push:
  #  branches: [ SBA-121 ]
  #pull_request:
  #  branches: [ SBA-121 ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    env:
      USER_HOME: $HOME

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Cache maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Cache npm
        uses: actions/cache@v2
        with:
          path: ~/.npm.docker
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      # Runs a single command using the runners shell
      - name: Build and run tests
        run: docker-compose -f "docker/maven/docker-compose.yml" up --exit-code-from juno-maven